# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  invoke:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -p path/to/artifact
    - run: cd path/to/artifact
    - run: curl -o path/to/artifact/result.txt https://j4fa1z4b5j.execute-api.ap-northeast-1.amazonaws.com/default/sample-nlp
    - uses: actions/upload-artifact@v3
      with:
        name: test-artiact
        path: path/to/artifact/result.txt
